lunar-linux/moonbase-core

crypto/openssl/DETAILS
=> openssl: version bumped to 1.0.1k.

libs/libidn/BUILD, libs/libidn/DEPENDS, libs/libidn/DETAILS
On my system works. Maybe we can considerate bumping it.
=> libidn: version bumped to 1.30.

system/systemd/CONFIGURE, system/systemd/DEPENDS, system/systemd/DETAILS, system/systemd/POST_INSTALL, system/systemd/PRE_BUILD, system/systemd/plugin.d/bootloader-systemd.plugin
- Added support for UEFI bootloader
- Tweaked depdencies list and added preferred defaults
- Added compat .pc files patch
- Added a couple of upstream fixes
- Tweaked which interface names that trigger the OLD naming scheme
=> systemd: version bump to 221 + various fixes

system/systemd/plugin.d/systemd.plugin
UNTESTED please review with care!
=> systemd.plugin: some refinements

editors/gawk/BUILD, editors/gawk/DEPENDS
=> gawk: it depends on mpfr.

security/Linux-PAM/BUILD, security/Linux-PAM/DETAILS, security/Linux-PAM/pam.d/system-auth
- rhel patches updated
- rhel modules bumped to 0.99.11
=> Linux-PAM: version bumped to 1.2.1

filesys/xfsprogs/BUILD, filesys/xfsprogs/DEPENDS, filesys/xfsprogs/DETAILS, filesys/xfsprogs/POST_INSTALL
=> xfsprogs: version bumped to 4.2.0.

utils/grep/BUILD, utils/grep/DEPENDS, utils/grep/DETAILS, utils/grep/POST_REMOVE
=> grep: version bumped to 2.22.

kernel/linux/DETAILS
=> linux: version bumped to 4.3.4

system/systemd/CONFIGURE, system/systemd/DEPENDS, system/systemd/DETAILS, system/systemd/POST_INSTALL, system/systemd/PRE_BUILD
=> systemd: version bumped to 228

system/systemd/BUILD, system/systemd/DEPENDS, system/systemd/DETAILS, system/systemd/PRE_BUILD
Incorporated some of florin's changes from PR #1115
Closes #1115
=> systemd: version bumped to 229

crypto/openssl/BUILD
=> Avoid passing through WANT_VERSION

security/iptables/DEPENDS, security/iptables/DETAILS
=> iptables: version bumped to 1.6.0.

crypto/openssl/POST_BUILD, crypto/openssl/POST_INSTALL
Takes care of migrating back from libressl to openssl.
=> openssl: Support migrating from libressl back to openssl.

shells/bash/DETAILS
=> bash: version bumped to 4.3.46.

system/dbus/BUILD
override the decision anyway with --enable-notify. So I am choosing one
and going with the if/esle.
=> dbus: You have the if/else to enable/disable inotify then in OPTS

system/systemd/BUILD, system/systemd/CONFIGURE, system/systemd/DEPENDS, system/systemd/DETAILS, system/systemd/PRE_BUILD
=> systemd: version bumped to 230

crypto/openssl/DETAILS
=> openssl: version bumped to 1.0.2i.

system/systemd/DETAILS, system/systemd/PRE_BUILD, system/systemd/plugin.d/systemd.plugin
Fixed small bug in systemd.plugin due to changes in systemctl enable output.
=> systemd: version bumped to 231

wifi/wpa_supplicant/BUILD, wifi/wpa_supplicant/DEPENDS, wifi/wpa_supplicant/DETAILS, wifi/wpa_supplicant/PRE_BUILD
=> Wpa supplicant 2.6 libressl

kernel/linux/DETAILS
=> linux: version bumped to 4.7.9.

editors/vim/DETAILS
This includes a rather long list of changes...
=> vim: they changed their release tarball

kernel/linux/DETAILS
=> linux: version bumped to 4.8.7

devel/flex/DETAILS, devel/flex/PRE_BUILD
see https://github.com/westes/flex/issues/113
=> flex: add a patch to fix a compatibility issue.

crypto/ca-certificates/DETAILS
The old file is not available anymore, so please merge
=> ca-certificates: version bump

crypto/ca-certificates/PRE_BUILD
I had to provide this fallback to make this script work with libressl.
=> ca-certificates: add libre-compatibility

fonts/terminus-font/BUILD, fonts/terminus-font/POST_INSTALL
on core we don't have the fonconfig, mkfontdir and mkfontscale apps.
=> terminus-font: fix the install.

utils/grep/DETAILS
=> grep: version bumped to 2.27.

chat/irssi/DETAILS
=> irssi: Version bumped to 1.0.0.

security/Linux-PAM/BUILD, security/Linux-PAM/DETAILS
=> Linux-PAM: version bumped to 1.3.0

utils/bc/BUILD, utils/bc/DEPENDS, utils/bc/DETAILS, utils/bc/POST_REMOVE
=> bc: version bumped to 1.07.1.

editors/vim/DETAILS
Seems the tarball was updated without bumping the version number.
=> vim: Updated the sha256sum.

utils/dialog/DETAILS
This new URL is awful.  It passes the sha256sum check though at least.
=> dialog: Their URL has changed.

compilers/gcc/DETAILS, compilers/gcc/plugin.d/optimize-gcc_7_2.plugin
=> gcc: version bumped to 7.2.0.

libs/glibc/BUILD
If you want to see what I actually did, do
diff BUILD BUILD.x86_64
The pull request diff is a bit unhelpful at best.
=> glibc: Fix 32-bit build by making it (mostly) identical to 64-bit.

utils/pciutils/DETAILS
Delete invalid link, fix Hash.
=> pciutils:Delete invalid link, fix Hash.

compilers/gcc/CONFIGURE
When did GCC stop supporting Java?
Also, Objective-C++!  Yo dawg, I heard you like objects so I put some
objects in your objects so you can orient while you orient.
=> gcc: Update the languages list to reflect what it actually offers.

libs/mpfr/DETAILS
=> mpfr: version bumped to 4.0.1.

archive/lzip/DETAILS
lzip:update download URL to https
=> lzip:update download URL to https

utils/util-linux/BUILD, utils/util-linux/PRE_BUILD
This is another thing breaking the daily build, but I have a feeling
there are better ways to fix this.
=> util-linux: Fix broken build (but install sulogin in /sbin)

editors/vim/DETAILS
It looks like Bram's been doing new releases without changing the
version number.  I hope he doesn't make a habit of doing that.
=> vim-8.1: Fix sha256sum.

crypto/libgpg-error/DETAILS
=> libgpg-error:Add download URL

devel/bison/DETAILS
=> bison:Bump to 3.0.5

filesys/acl/DETAILS
=> acl:change http to https

filesys/attr/DETAILS
=> attr:change http to https

editors/vim/BUILD, editors/vim/DEPENDS
They seem to be back to working again now.
=> vim: Reinstate the scripting languages that stopped working before.

doc-tools/re2c/BUILD, doc-tools/re2c/DETAILS
=> re2c: Adding to core moonbase.

utils/timezone-data/DETAILS
timezone-data:Change download URL to https
=> timezone-data:Change download URL to https

crypto/openssl/BUILD
If this works, daily ISOs will become functional again!
=> openssl: Fix the BUILD so that installwatch sees everything that happens.

archive/lzip/DETAILS
lzip:Change to available links.
=> lzip:Change to available links.

utils/dmidecode/DETAILS
dmidecode:Change download URL to https
=> dmidecode:Change download URL to https

perl/XML-Parser/DETAILS
=> XML-Parser:fix download URL

doc-tools/texinfo/DETAILS
=> texinfo:fix a typo

perl/perl/DETAILS
=> perl:change to https

python/python/BUILD, python/python/DETAILS
Really, we're not Python developers.  If you want to find a bug in
Python, go ahead and run all the tests.  For the rest of us, it just
slows everything down.
=> python: Just build and don't run the absurd test suite.

kernel/linux/DETAILS
=> linux:Change to https

kernel/linux-firmware/DETAILS
=> linux-firmware: Bump to 20190615.

crypto/libressl/DETAILS
fix SOURCE_VFY (This should never have happened!).
Supersedes #2138
=> [fix verification] libressl: version bump

kernel/kernel-headers/DETAILS, kernel/kernel-headers/DETAILS.x86_64
It's been more than a year since this one was updated.
=> kernel-headers: Version bumped to 5.1.10.

system/lunar/DETAILS
With this we might be able to bump bash too.
=> lunar: Version bump to 34

system/lunar/DETAILS
Closes https://github.com/lunar-linux/lunar/issues/139
=> lunar: version 35, fixes dependency installation issue

libs/expat/DETAILS
Security release.
Please commit AFAP.
=> expat: version bumped to 2.2.8.

devel/meson/DETAILS
=> meson:fix a typo

kernel/linux/DETAILS
We're currently lagging a version behind the version that's been EOL'ed!
=> Linux: Version bumped to 5.3.7

perl/XML-Parser/DETAILS
Also needed by the libqalculate bump.
=> XML-Parser: Bump to 2.46.

devel/make/BUILD, devel/make/DETAILS
If guile is requested, but not currently working for whatever reason, do whatever's necessary to at least provide your system with a working make so that other repairs can continue.
I suspect nobody's tested with a busted make command for a while. :)
=> Make: try harder to build

devel/meson/BUILD, devel/meson/DETAILS
Added dagbrown's build improvement.
=> meson: version bumped to 0.53.1.

editors/vim/DEPENDS
It's clearly a dependency I would not have thought of...
=> vim: make canberra optional

kernel/linux/DETAILS
=> linux:fix a typo

system/lunar/DETAILS
Mostly harmless refactoring and reformatting work preparatory to making
changes later.
=> lunar: Version bumped to 40

ftp/curl/DETAILS
Many fixes
https://curl.se/changes.html
=> curl: version bumped to 7.74.0

filesys/xfsprogs/DEPENDS, filesys/xfsprogs/DETAILS, libs/inih/BUILD, libs/inih/DEPENDS, libs/inih/DETAILS
It needs the inih module added to the base repository.
=> xfsprogs: version bumped to 5.10.0.

kernel/linux/DETAILS
=> linux: version bumped to 5.16.9

devel/cmake/BUILD, devel/cmake/DEPENDS, devel/cmake/DETAILS, devel/cmake/patch.d/cmake-cppflags.patch
cmake is now required by the latest version of json-c.
=> cmake: move it from other to core

libs/json-c/BUILD, libs/json-c/DEPENDS, libs/json-c/DETAILS
=> json-c: version bumped to 0.15

system/lunar/DETAILS
The loop detector is now feature toggled and off by default. 
Closes #3095
=> lunar: version bumped to 43

system/lunar/DETAILS
- Fixes an issue with reloading plugins during lin
=> lunar: version bumped to 44

system/grub2/PRE_BUILD
operating systems by grub when os-prober is run.
=> grub2: Adding a sedit in PRE_BUILD to enable the detection of other

archive/zlib/DETAILS
Tested on a laptop and 2 servers.
=> zlib: version bumped to 1.2.13

ftp/curl/DETAILS
Many fixes: https://curl.se/changes.html
=> curl: version bumped to 7.86.0

kernel/kernel-headers/DETAILS, kernel/kernel-headers/DETAILS.x86_64
Goes nicely with the new kernel and all.
=> kernel-headers: Version bump to 6.0.11

system/systemd/BUILD, system/systemd/POST_INSTALL
lunar fix python to POST_INSTALL to remove conflicting files.
=> systemd: Adding export PYTHONDONTWRITEBYTECODE=1 && to BUILD and

devel/cmake/DEPENDS
=> cmake: Adjusting DEPENDS, adding --system-librhash switch to fleshout

crypto/libgpg-error/DETAILS
=> libgpg-error

system/systemd/BUILD, system/systemd/DEPENDS, system/systemd/DETAILS
=> systemd: Version bumped to 254, and fix BUILD

devel/autoconf-archive/DEPENDS, devel/autoconf-archive/DETAILS
The autoconf-archive in other will need removing when this is added.
=> autoconf-archive: Adding. It is a depends for PR#3429 (dbus bump).

libs/expat/DETAILS
Opening the PR now, not finished testing dependants.
=> expat: version bumped to 2.6.0

archive/zlib/DETAILS
Add a backup URL for https://github.com/lunar-linux/moonbase-other/pull/3576#issuecomment-1953655483
=> zlib:add a URL

python/python-jinja2/DETAILS
duplicate of this module. I have in the wings commits for those modules that were dependent on python-jinja. So when you merge this I will push the others.
=> python-jinja2: I will be removing other/python-jinia as it is a

devel/ninja/BUILD, devel/ninja/DETAILS
This incorporates #3531, but also fixes the build.
=> ninja: bump to 1.12.0, fix build

crypto/openssh/DETAILS
=> openssh: version bumped to 9.8p1

kernel/linux/DETAILS
This is related to https://github.com/lunar-linux/moonbase-core/pull/3559
=> linux: version bumped to 6.9.8

kernel/kernel-headers/DETAILS.x86_64
https://hobby.esselfe.ca/lunar/spool/kernel-headers-6.9.8-x86_64.tar.bz2
=> kernel-headers: version bumped to 6.9.8

libs/glibc/DETAILS
Let's get this one going early to figure out whether it's good or not.
=> glibc: Version bump to 2.40

utils/installwatch/DETAILS
gcc 14.x fixes
- fix implicit function declaration in unit tests
- fix incorrect closing of file handles of type FILE *
=> installwatch: version bumped to 0.9.4

security/Linux-PAM/BUILD, security/Linux-PAM/DEPENDS, security/Linux-PAM/DETAILS, security/Linux-PAM/PRE_BUILD, security/Linux-PAM/pam.d/system-auth
=> Linux-PAM: bump version to 1.6.1 + updated patches

doc-tools/man/patch.d/man-1.6g-gcc-14.patch
gcc 14 is way stricter than earlier versions!
=> man: Add patch to make it build with gcc 14

security/cracklib/BUILD, security/cracklib/DETAILS
"Adjust dictionary generation to allow some special characters like quotes (xhanulik)."
=> cracklib: Bump to 2.10.1. An adjustment to dict since (quote);

compilers/gcc/DETAILS
We've done glibc and the kernel, now let's try the latest gcc!
=> gcc: Version bumped to 14.1.0

devel/pkgconf/BUILD, devel/pkgconf/DETAILS, devel/pkgconf/PRE_BUILD
Fix broken link for pkg-config man page.
=> pkgconf: version bumped to 2.3.0

system/systemd/DETAILS
=> Systemd: version bump to 255.17
