- kernel/kmod/DETAILS
- utils/usbutils/DETAILS
As the hardcoded URLs failed here, a small update to make them use the $KERNEL_SRC, to be sync with the user's configuration, nothing special, but it may help.
> Update kmod and usbutils to use $KERNEL_SRC

- crypto/openssl/DETAILS
> openssl: version bumped to 1.0.2a.

- archive/zlib/BUILD
- archive/zlib/DETAILS
The static build should be together with the shared lib.
> zlib: install libz.a to /lib together with the .so's

- libs/glib-2/plugin.d/postbuild-glib_compile_schemas.plugin
In some circumstances e.g. when gtk+-3 is updated apps begin to crash
when opening dialoges in apps, to resolve that the scheme
needs to be recompiled when a change is detected. This plugin
takes care of that.
> glib-2: added plugin to recompile gconf schemas

- editors/e3/BUILD
- editors/e3/DETAILS
"This version was reduced down to the minimum, i.e, armlinux, e3c and elks parts are removed,
if interested still use e3-2.7.1."
Does that bother us?
> e3: Bump to 2.8. Changes of interest to quote;

- net/libpcap/BUILD
- net/libpcap/DETAILS
The same issue bluez with 1.6.2 as with 1.7.4 (the make tanks here) so will
still run with 1.6.2 for now.
> libpcap: Adding a patch to deal with blue-5.x. Taken from arch linux.

- libs/elfutils/PRE_BUILD
i686 build produces a "might be used uninitialized" warning.
> elfutils: don't compile with -Werror

- crypto/openssl/DETAILS
Fixes a security issue and further fixes a previous issue.
> openssl: version bump to 1.0.2f

- chat/irssi/DETAILS
See https://github.com/irssi/irssi/releases for details.
> irssi: version bump to 0.8.18.

- aliases
Add libressl to the "%SSL" alias, and make a new alias "%OSSL"
which can be either openssl or libressl.
This is a teensy tiny harmless little change, to enable some much bigger changes soon.
> aliases: Add support for libressl

- utils/util-linux/BUILD
- utils/util-linux/DEPENDS
- utils/util-linux/DETAILS
enable last and wall. wall is needed to build apsupsd module.
> util-linux: version bumped to 2.28.

- devel/flex/BUILD
- devel/flex/PRE_BUILD
help2man is not in the core repo.
> flex: avoid build the man page if help2man is not installed

- archive/cpio/BUILD
- archive/cpio/DETAILS
- archive/cpio/POST_REMOVE
Removed the rmt app too. it's not needed anymore as tapes are obsolete now.
> cpio: version bumped to 2.12.

- crypto/openssl/DETAILS
Bug of the month club: there are failures in the AES-NI routines.
> openssl: Version bumped to 1.0.2h

- libs/gmp/BUILD
- libs/gmp/DETAILS
the flex module have to be sustained (removing it breaks gmp and gcc too)
> gmp: version bumped to 6.1.1.

- editors/nano/DETAILS
Error in /etc/nanorc on line 334: A syntax name must be quoted
It was quoted properly however somethings has changed in the recent nano bumps
and it no longer likes the space existing between "Java source", so replaced it
with a dash.
> nano: The java section was causing;

- crypto/libgpg-error/DETAILS
it's needed for the recent gnupg2 version.
> libgpg-error: version bumped to 1.24.

- chat/irssi/DEPENDS
- crypto/openssh/DEPENDS
- ftp/wget/BUILD
- mail/heirloom-mailx/PRE_BUILD
- net/iputils/DEPENDS
- wifi/wpa_supplicant/DEPENDS
This replaces https://github.com/lunar-linux/moonbase-core/pull/1179 .
> allow to use libressl instead of openssl throughout core

- crypto/ca-certificates/DETAILS
the previous archive is not on the host site anymore nor on Lunar's mirror
> ca-certificates: version bumped to 20161130

- utils/dialog/BUILD
the message was "configure: error: no curses library found"
> dialog: fixed a missing configure option

- devel/binutils/BUILD
- devel/binutils/DETAILS
Without this option `gcc -fuse-ld=gold` (as used e.g. by blender)
will fail because gcc forwards plugin options to the linker.
> binutils: enable -plugin for ld.gold

- devel/make/BUILD
The latest guile update broke my make executable.  This led to an
awkward situation.
Since make can bootstrap itself, this checks to see if make itself fell
over while trying to build itself, and uses the bootstrap script to
rescue itself.
> make: Fix the situation where make itself is broken.

- filesys/btrfs-progs/DETAILS
It's a good thing nobody uses btrfs, because this has been broken for
AGES.
> btrfs-progs: The sha256sum is broken.

- archive/lzip/BUILD
- archive/lzip/DETAILS
- archive/lzip/PRE_BUILD
- archive/lzip/plugin.d/unpack-lzip.plugin
Some GNU projects in moonbase-core (like ed) have switched from using
gzip to lzip to compress their tarballs, so I think lzip now also needs
to be in moonbase-core.
> lzip: Move lzip from moonbase-other to moonbase-core.

- editors/ed/DETAILS
This should probably be merged after lzip has been moved into the core
moonbase.
> ed: Version bump, change to ".lz" file suffix.

- crypto/ca-certificates/DETAILS
I'm not sure if "+nmu1" is a version bump or not, but they added
that too.  And added the version number, minus "+nmu1", to the
unpacked tarball, just to make things more challenging for us.
> ca-certificates: Fix URL, module directory

- utils/installwatch/BUILD
- utils/installwatch/DETAILS
- utils/installwatch/PRE_BUILD
'ln' in coreutils is now using symlinkat() which
resulted in missing symlinks in the cache tarballs.
> installwatch: added support for symlinkat()

- libs/glibc/DETAILS
- libs/glibc/PRE_BUILD
Stolen from
https://sourceware.org/git/gitweb.cgi?p=glibc.git;a=patch;h=388b4f1a02f3a801965028bbfcd48d905638b797
> glibc: Fix compile failure with newer binutils.

- system/os-prober/DETAILS
Also, annoyingly, the maintainers of os-prober deleted the previous
release.
> os-prober: Version bumped to 1.76.

- filesys/lvm2/DEPENDS
The circular dependency comes from the optional dependency
on cryptsetup. Thus we don't need to comment this out and
it actually breaks the iso building process.
@dagbrown inspired from one of your commits in your iso pull-request.
> lvm2: re-enable %UDEV dependency

- ftp/wget/DEPENDS
Now that pciutils and other low-level stuff is only available via https,
we can no longer consider SSL to be an optional dependency for wget.
(pciutils broke the ISO build!)
> wget: SSL support is no longer an optional thing.

- utils/installwatch/DETAILS
- utils/installwatch/PRE_BUILD
ld's initialization behavior for shared objects is a mess.
The order is pretty much arbitrary. In theory one can mark a library as
"initfirst" to avoid other shared objects initializing before,
but that's a *unique* mark and libpthread uses it already.
As a result LD_PRELOAD overlays the libc methods *from start*,
but until libinstallwatch is initialized (_init called),
libs end up calling invalid function pointers if they access an
overlayed libc method.
To fix this within installwatch, we have to check for successful
initialization in *each* method call...
Frustratingly, the llvm version of the latest rustc tries to access
the number of cores `open("/proc/cpuinfo")` during library initialization
(WHYYY?!) and thus segfaults if ld decides to load it before libinstallwatch.
And all I was …
> installwatch: patch to initialized if called uninitialized

- compilers/gcc/DETAILS
- compilers/gcc/plugin.d/optimize-gcc_7_2.plugin
Apparently it comes with SPECTRE v2 mitigation.  Otherwise it's just bug
fixes for gcc 7.2.0.
> gcc: Version bump to 7.3.0

- editors/vim/BUILD
- editors/vim/DETAILS
I was wondering the other day why my vim linked libx*
when I deactivated all GUI backends.
This change fixes it.
> vim without GUI should not link X

- filesys/btrfs-progs/DEPENDS
If you tell it not to build the Python 3 interface, it won't.  But
it defaults to assuming that you do want Python 3 support, and
fails hard if Python 3 isn't installed.  So make it not do that.
> btrfs-progs: Make Python 3 an optional dependency.

- utils/util-linux/DEPENDS
Making a default dependency on something outside of moonbase-core
will BREAK THE DAILY ISO BUILD.  Please do NOT do that.
Yes, Python-3 will eventually become the default Python.  But stop
breaking stuff in the name of attempting to force Python-3 in
where it's not welcome yet.
> util-linux: Fixing the Python dependency.

- perl/TimeDate/BUILD
- perl/TimeDate/DETAILS
- perl/URI/BUILD
- perl/URI/DETAILS
- perl/XML-Parser/BUILD
- perl/XML-Parser/DETAILS
Note: This is for testing only.  Do not merge until the next release of the `lunar` utility, which allows you to specify a module type to use a common build method, instead of having to put the same BUILD file in every similar module.
> Perl modules: use module type instead of BUILD file

- utils/util-linux/DEPENDS
Now that the default version of Python is 3, default to saying
"no" for the optional dependency on Python 2, and "yes" for Python
3.
> util-linux: Fix Python dependencies.

- libs/libidn2/BUILD
- libs/libidn2/DEPENDS
- libs/libidn2/DETAILS
- libs/libidn2/PRE_BUILD
- libs/libunistring/DETAILS
- net/iputils/DEPENDS
- net/iputils/DETAILS
It depends on libid2 which needs libunistring.
> iputils: version bumped to s20180629.

- archive/bzip2/BUILD
It seems to depend on bzip2 already being installed before being able to
link.
> bzip2: Add hack to fix bzip2 failing to link

- utils/installwatch/BUILD
- utils/installwatch/DETAILS
- utils/installwatch/PRE_BUILD
Adds a bunch of missing syscalls compared to our old version of installwatch.
This update is required Due to recent changes in coreutils where they switched
to newer *at syscalls which caused installwatch in lunar to miss a lot of files.
This update should remedy that.
> installwatch: lunars own fork, version 0.8.0rc2

- utils/findutils/DETAILS
- utils/findutils/patch.d/glibc-2.28.patch
I just took the code directly from the gnulib project, unchanged, so
this patch appears to have unrelated things in it.
> findutils: Patch the gnulib files that fail to build with glibc 2.28

- utils/coreutils/DETAILS
This is actually compatible with glibc 2.28!  So no need for an ugly
great patch.
> coreutils: Version bump to 8.30.

- system/systemd/DETAILS
- system/systemd/patch.d/systemd-resolvconf-fix.patch
Without the patch the resolvconf entries are dropped silently.
Required to have dhcpcd working with systemd-resolved
> systemd: backport fix for resolvconf

- crypto/openssl/BUILD
Check for the actual existence of /usr/lib64 before arbitrarily renaming
it /usr/lib first.
> openssl: I think maybe I was a bit overenthusiastic in my assumptions.

- system/systemd/DETAILS
- system/systemd/patch.d/meson-build.patch
- system/systemd/patch.d/meson-options.patch
Apparently it's used for its own internal things.  So let's call this
"debug-extra" and see if that works.
> systemd: meson doesn't like the option "debug" any more.

- libs/glibc/BUILD
- libs/glibc/BUILD.x86_64
Parts of the normal `make install` of glibc install things using a
system call that installwatch doesn't know about.  So until installwatch
is fixed, we're generating faulty ISOs with files missing.
This is a workaround for that.
> glibc: Change BUILD so that installwatch sees everything.

- libs/glibc/BUILD
- libs/glibc/BUILD.x86_64
This time round, save removing glibc altogether and just turn on
installwatch before the final copy.
> glibc: A few more moifications to the BUILD.

- archive/bzip2/DETAILS
The bzip.org we page has been replaced by a very default-looking
WordPress installation, and the file downloads went away.
> bzip2: Fix the URL.

- system/os-prober/DETAILS
The Debian guys removed their source tar ball for 1.76, so this fixes that.
> os-prober: Bump to version 1.77.

- system/efibootmgr/DETAILS
- system/efibootmgr/patch.d/fix-conflicting-declaration.patch
Specifically, the earlier hack was putting in a declaration for
efi_set_verbose, which turned out to be incorrect.
Whoopsie!
This fix is actually in the efibootmgr code that's on github, but there
hasn't been a release in a long time.
> efibootmgr: Add patch because an earlier hack broke the build

- libs/glibc/DEPENDS
This kind of needs to be made explicit when bootstrapping (like when
building an ISO).
> glibc: Now has a hard dependency on python.

- compilers/gcc/BUILD
Stripping these three executables makes the package half a gigabyte
smaller!  That's like more than half the size of the ISO right there.
> gcc: Make the package archive a lot smaller

- utils/installwatch/DETAILS
- added support for renameat2()
Required by https://github.com/lunar-linux/moonbase-core/pull/2187
> installwatch: version bumped to 0.8.0rc6

- filesys/lvm2/BUILD
Always ensure a directory exists before trying to install stuff into it.
> lvm2: Ensure dracut modules dir exists

- system/systemd/patch.d/0006-networkd-link-compilation-error-fix-b29afb9f.patch
systemd upstream fix b29afb9f3fe9a1d44accd7a47691bee9391c1db2
> systemd: fix compilation with latest gcc9

- libs/readline/DETAILS
- libs/readline/PRE_BUILD
This hasn't been updated in eight years!
Mainly because of all the trouble bumping readline causes on your live system.  It'd be nice for the ISO though.
> readline: Version bumped to 8.0.

- crypto/ca-certificates/DETAILS
- crypto/ca-certificates/patch.d/ssl_version_compatibility.patch
The current version actually got removed, which means that the normally-good advice to just "lin ca-certificates" whenever curl or wget stop working is now invalid.  Whoops.
> Ca-certificates: version bump to 20190110

- filesys/lvm2/BUILD
- filesys/lvm2/DEPENDS
- filesys/lvm2/DETAILS
- filesys/lvm2/POST_INSTALL
Please try this bump again, but maybe as a series of smaller changes over a few days next time.  This bump made the ISO unbootable, which is a problem.
> lvm2: Roll back bump to 2.03.04

- utils/timezone-data/DETAILS
- utils/timezone-data/PRE_BUILD
- utils/timezone-data/patch.d/makefile.patch
This bumps the timezone-data version to 2019b, and moves the Makefile patch into the moonbase.
> Timezone data 2019b

- shells/bash_static/DETAILS
It's amazing how long this has been like this and never been noticed.
It's because bash_static has always been the same version as bash, so
it's never needed to be downloaded separately.
> bash_static: Fix the URL so it looks for bash, not "bash_static".

- system/efivar/DETAILS
- system/efivar/patch.d/b98ba8921010d03f46704a476c69861515deb1ca.patch
- system/efivar/patch.d/c3c553db85ff10890209d0fe48fb4856ad68e4e0.patch
From:
https://github.com/rhboot/efivar/commit/b98ba8921010d03f46704a476c69861515deb1ca.patch
https://github.com/rhboot/efivar/commit/c3c553db85ff10890209d0fe48fb4856ad68e4e0.patch
As reported in:
https://github.com/rhboot/efivar/issues/127
> efivar: Add patches to get it to compile under gcc 9.

- system/dbus/BUILD
It seems that the latest version of shadow doesn't let you add
users with an invalid shell.  The `false` binary is in /usr/bin,
not in /bin.
> dbus: Fix adding the "messagebus" user.

- devel/meson/BUILD
I did this because I fixed default_python3_build so that it doesn't
trust the handiwork of setuptools as much any more, and has it install
into a DESTDIR instead.
> meson: Fix the build to use default_python3_build.

- system/lunar/DETAILS
This fixes the broken ISO (thanks to bad_flags, ONCE AGAIN), and adds some code to deal with obsolete modules (which I'm not sure is actually used yet).
> lunar: Version bump to 39.

- crypto/cryptsetup/DETAILS
- libs/libcap/DETAILS
- net/iproute2/DETAILS
URLs that start at "https://www.kernel.org/" redirect via
"https://mirrors.edge.kernel.org/" which then (theoretically)
redirects on to "https://mirrors.kernel.org", which currently
has an expired SSL certificate.
So skip all the redirecting and just start at "mirrors.kernel.org".
> kernel.org-hosted modules: Change download URL

- libs/ncurses/DETAILS
This reverts commit e37a936198ba39516ec3863c18b9d191fea4978d.
bumping ncurses nearly always causes the daily to fail, and this time is
no exception.
> Revert "ncurses: version bumped to 6.2."

- compilers/gcc/DETAILS
- compilers/gcc/plugin.d/optimize-gcc.plugin
This was mainly a relict from times when it made sense to have different GCC versions around.
From now on, we have to make sure not to add backward incompatible default options to the plugin though,
as these would affect the previously installed version during the upgrade.
> remove gcc version from plugin

- crypto/openssh/DETAILS
- crypto/openssh/systemd.d/sshd.service
- crypto/openssh/systemd.d/sshd@.service
Standard output type syslog is obsolete, automatically updating to journal.
Please update your unit file, and consider removing the setting altogether.
> openssh: Removing StandardOutput from the service files for this reason;

- libs/gnu-efi/BUILD
Fix module compilation. Upstream requires `-mno-sse` and compiles with -Werror.
> disable sse for gnu-efi

- devel/binutils/DETAILS
- libs/mpfr/DETAILS
This undoes the version bump to 2.35.1, which broke efivar and thus the daily ISO.
Let's find a patch to fix efivar (or hope for a new release) and then bump again.
> Binutils rollback to 2.34

- libs/libidn2/DEPENDS
- libs/libidn2/PRE_BUILD
Libidn2: Fix the prebuild to deal with both the presence and absence of gtk-doc.
> Libidn2 fix prebuild

- utils/util-linux/BUILD
- utils/util-linux/DETAILS
mount.fuse3, mount.sshfs, and mount.crypt (pam_mount) install to /usr/sbin.
Some recent change broke my pam_mount setup that mounts my home folder upon login.
After two hours of debugging I figured out that the defaults call `mount -t crypt`
and expect the `mount.crypt` helper to be called.
> [fix] util-linux: allow mount helpers in /usr/sbin

- crypto/openssl/BUILD
This instead of adding a BUILD.x86_64 file, which is apparently too
clunky.
> openssl: Add 128bit-integer-based option based on arch

- compilers/gcc/plugin.d/optimize-gcc.plugin
The detection is still done through the CPU ABM flag, but gcc's -mabm flag
is just a shorthand for -mpopcnt -mlzcnt . Because we already handle
popcnt separately and because clang does not support the shorthand,
it's better to set lzcnt directly.
> gcc plugin: replace ABM option by LZCNT

- filesys/lvm2/BUILD
For some reason, gcc 10.2 forgets about the -shared flag if it's too
early on the command line, but only on i686 builds. This ugly hack adds
an extra "-shared" later on so that it remembers what it was supposed to
be doing, so that lvm2 can build in a 32-bit environment.
> lvm2: Fix build for gcc 10.2 on i686

- python/python/DEPENDS
removed the second 'w' in --wwith-system-libmpdec
> python - fix typo in DEPENDS

- devel/meson/DEPENDS
There is literally no reason for meson to have a hard dependency on
rsync. Do the devs not know about the cp command?
> meson: Rolback PR #2796

- devel/meson/DEPENDS
I'm going to keep meson rolled back until I figure out why on earth it
seems to think it depends on rsync (I have a feeling it doesn't).
Until then, adding the rsync dependency has unfortunately done an
excellent job of breaking the dailies. Sorry!
> rolling-back 2796: meson: rsync isn't in moonbase-core (yet)

- system/systemd/patch.d/0002-lunar-iso-build.patch
Instead of simply asking politely to not use rsync, just put in a
heavy-handed patch to make it unnecessary. I don't like this, even a
little bit.
> systemd: Hack to make systemd build on the ISO build

- filesys/ntfs-3g/DEPENDS
Having it default to "y" breaks the ISO build, so let it be off by
default instead.
> ntfs-3g: Make the answer for the gnutls dependency default to "n"

- archive/zlib/DETAILS
This is a security update. For bonus points, they also deleted 1.2.11
from their site altogether, which means that if this isn't bumped, the
daily builds will fail altogether.
> zlib: Version bump to 1.2.12

- archive/xz/DETAILS
- archive/xz/patch.d/xzgrep-ZDI-CAN-16587.patch
Add patch from https://tukaani.org/xz/ fixing CVE-2022-1271.
gzip already has a PR open about 1.12
> xz: add security patch (CVE-2022-1271)

- kernel/linux-firmware/BUILD
- kernel/linux-firmware/CONFIGURE
- kernel/linux-firmware/DETAILS
- kernel/linux-firmware/PRE_BUILD
- kernel/linux-firmware/patch.d/0001-Add-support-for-compressing-firmware-in-copy-firmware.patch
Changes:
- Less commonly used firmware will default to not being installed
- All firmware is now xz compressed, requires
CONFIG_FW_LOADER_COMPRESS to be enabled in the kernel
> linux-firmware: version bumped to 20220809

- kernel/kernel-headers/DETAILS
This definitely needs to be updated if there's going to be any hope of
making an i686 ISO ever again.
Besides, having two different versions for the different architectures is really ugly.
> Kernel-headers (i686 version): Version bump to 5.19.2.

- system/dbus/POST_INSTALL
It's been dead since 2018 at least
> dbus: Stop trying to check for gtk-sharp

- libs/libunistring/BUILD
Remove the sedit in BUILD since it wants an occurrence that doesn't exist anymore.
> libunistring: version bumped to 1.1

- net/libmnl/BUILD
- net/libmnl/DEPENDS
Some people might actually want the doxygen-generated documentation.
This incorporates #3140
> Libmnl: make doxygen optional

- crypto/cryptsetup/DEPENDS
- crypto/cryptsetup/DETAILS
This incorporates #3147, but makes the extra dependencies optional so that they don't need to be added to moonbase-core.
> Cryptsetup 2.5.0

- libs/expat/DETAILS
> expat: version bumped to 2.5.0, security fix

- crypto/openssl/DETAILS
This is a big bump and breaks lots of things, especially:
* sbsigntools
* efitools
So please not to be merging this until at least those two are resolved.
> openssl: Version bump to 3.0.3

- libs/libffi/BUILD
- python/python/POST_INSTALL
disabling static in BUILD. While testing chromium bump the make failed on libffi_pic.a which is provided by the tarball. In chromiums linux/libffi/BUILD.gn it says system libffic must be compile statically. Doing this the build progressed beyond the error.
> Libffi Disabling static 

- libs/pcre2/BUILD
- libs/pcre2/DEPENDS
- libs/pcre2/DETAILS
The latest glib2 insists that pcre2 be present, and insists so hard that it tries to download it if it's not already installed.
> pcre2: moving from other to core

- libs/glib-2/BUILD
- libs/glib-2/DEPENDS
- libs/glib-2/DETAILS
Our current version of glib-2 to old for the current gobject-introspection which will silently pull in the version of glib-2 it needs. The problem with that it stomps on the system glib-2. So a install or recompile of gobject-introspection will fail leaving you with a broken glib-2 and the reason for https://github.com/lunar-linux/moonbase-other/issues/2262.
> glib-2: Bump to 2.76.0 and removing the invalid switch.

- utils/dmidecode/DETAILS
If it fails to grab the tarball blame savannah. Couldn't fine a reliable server.
> dmidecode: Bump to 3.5.

- python/python-setuptools/DETAILS
The modules in core dependent on setuptools went ok. A wholly incomplete test of other python modules went ok. Cannot guarantee no issues.
> python-setuptools: Bump to 67.4.0.

- archive/xz/DETAILS
xz 5.4.2 still gives a warning:
`xz: Reduced the number of threads from 1 to one. The automatic memory usage limi
t of 242 MiB is still being exceeded. 1250 MiB of memory is required. Continuing
anyway.`
So opt for the old 5.2 branch instead
> xz: version bumped to 5.2.11

- archive/xz/DETAILS
About xz 5.4 giving the warning:  
`xz: Reduced the number of threads from 1 to one. The automatic memory usage limi t of 242 MiB is still being exceeded. 1250 MiB of memory is required. Continuing anyway.`  
Well that can be fixed by setting COMPRESS_METHOD_ARGS="-T 1"
I think this remains to be fixed in the lunar source... like when you go in the features menu it sets it back to "-T 0"
> xz: version bumped to 5.4.3

- utils/pciutils/DETAILS
of SOURCE2_URL (pci id db) of PR 3181.
> pciutils: Bump to 3.10.0 and incorporates the location change

- crypto/ca-certificates/DETAILS
- crypto/ca-certificates/patch.d/python-cryptography-elimination.patch
This one's a bit urgent because the previous one's been removed from the download location so ca-certificates updates will definitely fail
> ca-certificates: Version bumped to 20230311

- system/grub2/patch.d/grub2-ignore_ext4_checksum_seed_feature.patch
Recently e2fsprogs 1.47.0 has enabled the metadata_csum_seed feature by default and grub-install fails to recognize the filesystem with this.
The patch found on https://lists.gnu.org/archive/html/grub-devel/2021-06/msg00031.html had to be regenerated.
> grub2: add patch to fix installation errors with new e2fsprogs 1.47.0

- net/iproute2/DETAILS
The original website URL redirects to the wiki, so use that instead.
> iproute2: version bumped to 6.5.0

- ftp/curl/DEPENDS
- ftp/curl/DETAILS
Fixes CVE-2023-38039 : HTTP headers eat all memory (https://curl.se/docs/CVE-2023-38039.html)
Also nss support has been removed.
> curl: version bumped to 8.3.0 (security)

- utils/procps/DETAILS
This version fixes the msgstr problem with gettext 0.22 to 0.22.2
The error message was:
fr.po:3801: msgstr is not a valid C format string, unlike msgid. Reason: In the directive number 4, the argument size specifier is invalid.
> procps: version bumped to 4.0.4

- ftp/curl/DETAILS
Fixes CVE-2023-38545 (SOCKS5 heap buffer overflow) and CVE-2023-38546 (cookie injection flaw).
> curl: version bumped to 8.4.0, security fix

- libs/libusb-compat/BUILD
- libs/libusb-compat/DETAILS
appears all they did was remove the need for autogen.sh.
> libusb-compat: Fixing up DETAILS and BUILD. No version bump here. It

- libs/popt/BUILD
The error I was getting was:
[...]
libtool: install: /bin/install -c .libs/libpopt.lai /usr/lib/libpopt.la                                                       
libtool: install: /bin/install -c .libs/libpopt.a /usr/lib/libpopt.a                                                          
libtool: install: chmod 644 /usr/lib/libpopt.a                                                                                
libtool: install: ranlib /usr/lib/libpopt.a                                                                                   
../libtool: line 1720: 3593883 Segmentation fault      (core dumped) ranlib /usr/lib/libpopt.a
I believe this situation only occurs on the aarch64 architecture. I've read somewhere that it might have to do with running in a chroot, but I can't test on a …
> popt: fix build on aarch64 systems

- libs/libunistring/BUILD
Same problem as in https://github.com/lunar-linux/moonbase-core/pull/3407
I've tried recompiling all that depends on this, everything seems fine without libunistring.a
> libunistring: fix build failure on aarch64

- libs/libffi/BUILD
This is for the same problem as popt (https://github.com/lunar-linux/moonbase-core/pull/3407)
The error I was getting was:
[...]
make[3]: Entering directory '/usr/src/libffi-3.4.4/aarch64-unknown-linux-gnu'
/bin/mkdir -p '/usr/lib/pkgconfig'
/bin/mkdir -p '/usr/lib'
/bin/sh ./libtool   --mode=install /bin/install -c   libffi.la '/usr/lib'
/bin/install -c -m 644 libffi.pc '/usr/lib/pkgconfig'
libtool: install: /bin/install -c .libs/libffi.so.8.1.2 /usr/lib/libffi.so.8.1.2
libtool: install: (cd /usr/lib && { ln -s -f libffi.so.8.1.2 libffi.so.8 || { rm -f libffi.so.8 && ln -s libffi.so.8.1.2 libffi.so.8; }; })
libtool: install: (cd /usr/lib && { ln -s -f libffi.so.8.1.2 libffi.so || { rm -f libffi.so && ln -s libffi.so.8.1.2 libffi.so; }; })
libtool: install: /bin/install -c …
> libffi: another static-disabling fix for aarch64 build

- libs/libidn2/BUILD
Same problem as popt (https://github.com/lunar-linux/moonbase-core/pull/3407)...
The error I got was:
[...]
make[4]: Entering directory '/usr/src/libidn2-2.3.4/lib'                                                                      
/bin/mkdir -p '/usr/lib'                                                                                                     
/bin/mkdir -p '/usr/include'                                                                                                 
/bin/sh ../libtool   --mode=install /bin/install -c   libidn2.la '/usr/lib'                                                  
/bin/install -c -m 644 idn2.h '/usr/include'                                                                                 
libtool: install: /bin/install -c .libs/libidn2.so.0.3.8 …
> libidn2: fix build on aarch64 (disable static)

- filesys/dmraid/BUILD
This time the error I was getting was:
[...]
\+ ./configure --build=aarch64-linux-gnu --prefix=/usr --sysconfdir=/etc --localstatedir=/var --infodir=/usr/share/info --mandi
r=/usr/share/man                                                                                                              
checking build system type... Invalid configuration 'aarch64-linux-gnu': machine 'aarch64' not recognized                     
configure: error: /bin/sh autoconf/config.sub aarch64-linux-gnu failed
> dmraid: fix build on aarch64

- utils/wipe/BUILD
The error I was getting was:
configure: error: can not guess host type; you must specify one
> wipe: fix build on aarch64

- utils/pciutils/DEPENDS
- utils/pciutils/DETAILS
Even though nothing in core is supposed to be downloading anything from the Internet as part of its build (because if you're building an ISO, by definition you'll have an incomplete system), pciutils thinks that it's special and insists on downloading a new pci.ids file just in case it's changed in the last half hour or so.
(The pci.ids file chagnes on average once a month. It's not that special.)
So until there's a better fix, just add another layer of stupid, ugly hackwork on top of the existing pile of problems.
> pciutils: Add hard dependency on wget

- ftp/curl/DETAILS
Fixes [CVE-2023-46218](https://curl.se/docs/CVE-2023-46218.html) and [CVE-2023-46219](https://curl.se/docs/CVE-2023-46219.html)
> curl: version bumped to 8.5.0 (security fixes)

- crypto/openssh/BUILD
- crypto/openssh/DETAILS
There's 2 sedit commands changing PermitRootLogin, one in PRE_BUILD and one in BUILD.
Let's keep the one that's working :P
> openssh: version bumped to 9.6p1

- archive/xz/DETAILS
Seems like the original site doesn't host the archives anymore.
> xz: version bumped to 5.4.6 + new URL

- ftp/curl/DETAILS
The new URL is taken from a redirect.
> curl: version bumped to 8.6.0

- crypto/openssh/CONFIGURE
- crypto/openssh/DETAILS
In the configure script it defaults to no for now, so also default to no in the mquery.
> openssh: version bumped to 9.7p1 + new DSA option

- archive/xz/DETAILS
See:
https://arstechnica.com/security/2024/03/backdoor-found-in-widely-used-linux-utility-breaks-encrypted-ssh-connections/
Someone managed to sneak a backdoor into xz 5.6 and it hasn't been fixed in the xz mainline yet, so rolling back to before it was introduced.
> xz: Roll back bumps to 5.6.0, 5.6.1.

- python/python/BUILD
- python/python/DEPENDS
- python/python/DETAILS
- python/python/PRE_BUILD
Also hopefully made it so mpdecimal doesn't need to be moved into moonbase-core just to support Python.
> Python: Version bumped to 3.12.3

- filesys/btrfs-progs/DEPENDS
- filesys/btrfs-progs/DETAILS
This version builds fine with the latest e2fsprogs (https://github.com/lunar-linux/moonbase-core/pull/3547).
> btrfs-progs: version bumped to 6.9

- crypto/libxcrypt/BUILD
- crypto/libxcrypt/DETAILS
The latest glibc doesn't include libcrypt (by default--but the devs have threatened to take it away altogether, so I'm preparing for that day here), so here's its replacement, libxcrypt.
Also some changes to libxcrypt to install into /usr/lib and /usr/include instead of /usr/lib/libxcrypt and /usr/include/libxcrypt respectively, on account of how without those things handy, an awful lot of the system will break.
> Libxcrypt: move to core

- libs/readline/BUILD
This is related to https://github.com/lunar-linux/moonbase-other/pull/3755 which I was rewriting to cmake... so rpm-tools can't find readline's pkgconfig files in /lib/pkgconfig/. No clues why it doesn't search there though. I thought putting a link at the correct place could also help with other modules having this hiccup, probably part of the usrmerge movement, who knows :P
> readline: add pkgconfig links in proper location

- devel/binutils/BUILD
I was getting this on my Oracle server:
Removed module: binutils
cp: cannot overwrite non-directory '/usr/lib64' with directory '/usr/src/binutils-2.42/__destdir/usr/lib64'
So include the aarch64 arch for the fix as well.
> binutils: fix installation on aarch64

- mail/s-nail/DETAILS
Also, replace its URL with the official s-nail release URL instead of the Debian cache
> s-nail: Version bump to 14.9.25

- filesys/e2fsprogs/BUILD
In file included from /usr/include/fuse/fuse.h:26,
from /usr/include/fuse.h:9,
from fuse2fs.c:29:
/usr/include/fuse/fuse_common.h:33:2: error: #error Please add -D_FILE_OFFSET_BITS=64 to your compile flags!
33 | #error Please add -D_FILE_OFFSET_BITS=64 to your compile flags!
|  ^~~~~
CC mklost+found.c
CC filefrag.c
CC e2freefrag.c
make[2]: *** [Makefile:472: fuse2fs.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/usr/src/e2fsprogs-1.47.1/misc' make[1]: *** [Makefile:445: all-progs-recursive] Error 1 make[1]: Leaving directory '/usr/src/e2fsprogs-1.47.1' make: *** [Makefile:373: all] Error 2
> e2fsprogs:add -D_FILE_OFFSET_BITS=64 to compile flags

- ftp/curl/DEPENDS
- ftp/curl/DETAILS
Fixes [CVE-2024-7264](https://www.cvedetails.com/cve/CVE-2024-7264/)
> curl: version bumped to 8.9.1

- kernel/kernel-headers/DETAILS.x86_64
The tarball is prepared here: https://hobby.esselfe.ca/src/kernel-headers-6.10.2-x86_64.tar.bz2
> kernel-headers: version bumped to 6.10.2

- kernel/linux/DETAILS
This PR needs systemd 254.16 to succeed. See https://github.com/lunar-linux/moonbase-core/pull/3580
> linux: version bumped to 6.10.2

- crypto/openssl/DETAILS
> openssl: Bump to 3.3.2. Current moonbase version is to old

- crypto/openssh/CONFIGURE
- crypto/openssh/DETAILS
This release now defaults to disabling DSA keys at build time, so change CONFIGURE accordingly.
> openssh: version bumped to 9.9p1

- utils/timezone-data/DETAILS
The excellent news is that IANA is no longer just deleting all old releases of timezone-data, so the ISO builds haven't been breaking whenever a new tzdata is released.
The downside of that is that it's easy to forget to bump it every now and then.
> timezone-data: Version bumped to 2024b

- kernel/dracut/PRE_BUILD
The "xsltproc" invocations in the dracut Makefile is trying to use a XSLT stylesheet downloaded from docbook.sourceforge.net (non-SSL HTTP even!). But these stylesheets are already available on the system if asciidoc is installed! So use the local copies instead of trying (and failing) to download them instead.
Now we can finally have man pages for our dracut installations.
> dracut: Use local XSLT resources instead of trying to download them

- kernel/kernel-headers/DETAILS.x86_64
Headers tarball here: https://hobby.esselfe.ca/src/kernel-headers-6.11.1-x86_64.tar.bz2
> kernel-headers: version bumped to 6.11.1

- kernel/dracut/DETAILS
Trying out dracut-ng (as used by Arch Linux) because it seems to have considerably more lively development than the Red Hat one.
> dracut: Switching to dracut-ng, version bump to 103

- ftp/wget/DETAILS
** [Breaking change] Drop support for shorthand FTP URLs (CVE-2024-10524)
** [Breaking change] Switch to continuous reading from stdin pipes
** Reimplement user-info parsing based on RFC 2396
** Fix a build issue with libproxy and --disable-debug
> wget: Bump to 1.25.0. Their note worthy changes;

- kernel/kernel-headers/DETAILS.x86_64
Tarball here: https://hobby.esselfe.ca/src/kernel-headers-6.12.1-x86_64.tar.bz2
> kernel-headers: version bumped to 6.12.1

- utils/file/DETAILS
File 5.46 returns "data" for some zip archives, like sqlite and brave-bin. The issue is it downloads the archive, but then goes to the fallback mirror and fails. The actual call is in /var/lib/lunar/functions/download.lunar and the 'file -b' output is supposed to contain "Zip" but now it's "data".
See the bug tracking thread on https://bugs.astron.com/view.php?id=571 . Apparently it's been fixed on the main branch and we're waiting for 5.47.
> file: revert to 5.45, some zip files not recognized

- filesys/lvm2/BUILD
- filesys/lvm2/DETAILS
Remove code for non-x86_64 systems since the build on x86 fails with this.
> lvm2: version bumped to 2.03.29

- devel/binutils/BUILD
- devel/binutils/DETAILS
More infos about the gold linker removal here: https://www.phoronix.com/news/GNU-Gold-Linker-Deprecated
> binutils: version bumped to 2.44 + remove gold

- crypto/openssh/DETAILS
Changes since OpenSSH 9.9p1
===========================
This release fixes two security bugs.
Security
========
* Fix CVE-2025-26465 - [ssh(1)](https://man.openbsd.org/ssh.1) in OpenSSH versions 6.8p1 to 9.9p1
(inclusive) contained a logic error that allowed an on-path
attacker (a.k.a MITM) to impersonate any server when the
VerifyHostKeyDNS option is enabled. This option is off by default.
* Fix CVE-2025-26466 - [sshd(8)](https://man.openbsd.org/sshd.8) in OpenSSH versions 9.5p1 to 9.9p1
(inclusive) is vulnerable to a memory/CPU denial-of-service related
to the handling of SSH2_MSG_PING packets. This condition may be
mitigated using the existing PerSourcePenalties feature.
> openssh: version bumped to 9.9p2

- crypto/openssl/DETAILS
Fixes 3 CVEs:
- [CVE-2024-12797](https://www.openssl.org/news/vulnerabilities.html#CVE-2024-12797)
- [CVE-2024-13176](https://www.openssl.org/news/vulnerabilities.html#CVE-2024-13176)
- [CVE-2024-9143](https://www.openssl.org/news/vulnerabilities.html#CVE-2024-9143)
> openssl: version bumped to 3.3.3

- utils/util-linux/BUILD
/usr/lib/tmpfiles.d/uuidd-tmpfiles.conf:6: Failed to resolve user 'uuidd': No such process
> util-linux: Adding privilaged group/user uuidd to silence;

- devel/cmake/DETAILS
Even though this worked with the future builds, it broke the daily ISO.
> Rollback #3742 (cmake: Bump to 3.31.4)

- kernel/kernel-headers/DETAILS.x86_64
Headers tarball here: https://hobby.esselfe.ca/src/kernel-headers-6.14.1-x86_64.tar.bz2
> kernel-headers: version bumped to 6.14.1

- filesys/ntfs-3g/BUILD
- filesys/ntfs-3g/DEPENDS
in BUILD. Do a autoreconf so it will properly fine libgcrypt.
> ntfs-3g: Removing fuse optional_depends and go with internal as noted

- python/python/POST_INSTALL
Currently if you answer "n" to the query to upgrade Python modules, the POST_INSTALL exits with 1 and lin aborts. This is a problem when you're trying to lin something with Python as a dependency.
> python: POST_INSTALL should always exit with success

- kernel/kernel-headers/DETAILS.x86_64
Headers tarball here: http://esselfe.ca/lunar/spool/kernel-headers-6.15.2-x86_64.tar.bz2
> kernel-headers: version bumped to 6.15.2

- filesys/ntfs-3g/BUILD
- filesys/ntfs-3g/DETAILS
This new one (at a new home on github) needs you to run autogen.sh before attempting to compile the module.
> ntfs-3g: new source code bundle

- archive/zstd/BUILD
- archive/zstd/DEPENDS
files get created and installed for those apps looking for them. Also added lzma-sdk as an optional_depends.
> zstd: No version bump, just using cmake instead so various *.cmake

- python/python/BUILD
- python/python/DETAILS
care to deal with any fallout from the latest. The recent tk/tcl bumps (20250731) was causing python to fail compile. Also removing an invalid switch from BUILD.
> python: Bump to 3.12.11. Yes its not the latest and greatest and I don't
